baseURL = "https://example.org"
languageCode = "en-us"
disableKinds = ["taxonomy", "term"]
theme = "rename-this-theme"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.83.1"

[build]
# Used by PurgeCSS
writeStats = true