[build]
publish = "public"
command = "yarn build"

[context.production.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy]
command = "yarn build:netlify:branch"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.deploy-preview]
command = "yarn build:netlify:preview"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "script-src 'self' 'unsafe-inline'"
